- name: installing golang
  ansible.builtin.yum:
    name: golang
    state: installed

- name: app prerequisite
  ansible.builtin.import_role:
    name: common
    tasks_from: app_presetup.yml

- name: load the dependencies
  ansible.builtin.command:
    cmd:  go mod init dispatch
    chdir: /app

- name: load the dependencies
  ansible.builtin.command:
    cmd:  go mod init dispatch
    chdir: /app

- name: load the dependencies
  ansible.builtin.command:
    cmd:  go get
    chdir: /app

- name: load the dependencies
  ansible.builtin.command:
    cmd:  go build
    chdir: /app


- name: systemd setup
  ansible.builtin.import_role:
    name: common
    tasks_from: systemd_setup.yml
