- name: updating prometheus config
  ansible.builtin.template:
    src: prometheus.yml
    dest: /opt/prometheus/prometheus.yml


- name: restarting the prometheus
  ansible.builtin.systemd:
    name: prometheus
    state: restarted