- name: updating prometheus config
  ansible.builtin.template:
    src: prometheus.yml
    dest: /etc/systemd/system/prometheus.service

- name: restarting the prometheus
  ansible.builtin.systemd:
    name: prometheus
    state: restarted