 - name: adding user
   ansible.builtin.user:
     name: roboshop
    
 - name: removing directory
   ansible.builtin.file:
     path: /app
     state: absent

 - name: create a directory
   ansible.builtin.file:
     path: /app
     state: directory
     
 - name: downloading and extracting component
   ansible.builtin.unarchive:
       src: https://roboshop-artifacts.s3.amazonaws.com/{{component}}.zip
       dest: /app
       remote_src: yes