 - name: setup systemd setup
   ansible.builtin.template:
     src: mongo.repo
     dest: /etc/yum.repos.d/mongo.repo
     
 - name: installing mongo client
   ansible.builtin.yum:
     name: mongodb-org-shell
     state: installed
     
 - name: load the schema
   ansible.builtin.shell: mongo --host mongodb-dev.devopspractice.lol </app/schema/{{ component }}.js